import type { EstadoEvento } from "@/domain/enums/EstadoEvento";
import type { MedioPago } from "@/domain/enums/MedioPago";

export type EventoResponse = {
  id: number;
  puntoDeVentaId: number;
  comedorId: number;
  tipoEventoId: number;
  tipoEventoNombre: string;
  estado: EstadoEvento;
  medioPago: MedioPago;
  fechaEvento: string;
  fechaEmision: string;
  fechaPago: string;
  solicitanteId: number;
  emailSolicitante: string;
  funcionarioId: number;
  funcionarioNombre: string;
  responsableId: number;
  responsabeNombre: string;
  cantidadPersonas: number;
  precioUnitario: number;
  montoTotal: number;
  numeroOperacion: string;
  razonSocial: string;
  destinatarioFacturacion: string;
  tipoComprobante: string;
  numeroComprobante: string;
  observaciones: string;
  retenciones: number;
  facturaPdfObjectKey: string;
  facturaPdfNombreArchivo: string;
  facturaPdfContentType: string;
  facturaPdfByteSize: number;
  facturaPdfSubidoEn: string;
  creadoEn: string;
  actualizadoEn: string;
  creadoPorId: number;
  anulacionId: number;
};
